insert into discount (discount_id, name, description, percent) values (1, 'Karlan', 'Brandy - Bar', 36);
insert into discount (discount_id, name, description, percent) values (2, 'Jermaine', 'Loaf Pan - 2 Lb, Foil', 75);
insert into discount (discount_id, name, description, percent) values (3, 'Dusty', 'Soup - Knorr, Country Bean', 71);
insert into discount (discount_id, name, description, percent) values (4, 'Vidovic', 'Soup - French Can Pea', 86);
insert into discount (discount_id, name, description, percent) values (5, 'Cece', 'French Kiss Vanilla', 66);
insert into discount (discount_id, name, description, percent) values (6, 'Pryce', 'Tea - Lemon Scented', 73);
insert into discount (discount_id, name, description, percent) values (7, 'Nerita', 'Tea - Green', 19);
insert into discount (discount_id, name, description, percent) values (8, 'Zacharie', 'Potatoes - Yukon Gold, 80 Ct', 51);
insert into discount (discount_id, name, description, percent) values (9, 'Bernice', 'Veal - Heart', 49);
insert into discount (discount_id, name, description, percent) values (10, 'Merrile', 'Tofu - Firm', 46);
insert into discount (discount_id, name, description, percent) values (11, 'Milli', 'Shortbread - Cookie Crumbs', 34);
insert into discount (discount_id, name, description, percent) values (12, 'Bobbie', 'Buffalo - Short Rib Fresh', 59);
insert into discount (discount_id, name, description, percent) values (13, 'Gerhardine', 'Chambord Royal', 4);
insert into discount (discount_id, name, description, percent) values (14, 'Crystie', 'Cocoa Butter', 46);
insert into discount (discount_id, name, description, percent) values (15, 'Jeremie', 'Salsify, Organic', 43);
insert into discount (discount_id, name, description, percent) values (16, 'Thurston', 'Beef - Ox Tail, Frozen', 93);
insert into discount (discount_id, name, description, percent) values (17, 'Reed', 'Coffee - Dark Roast', 5);
insert into discount (discount_id, name, description, percent) values (18, 'Josselyn', 'Pasta - Spaghetti, Dry', 65);
insert into discount (discount_id, name, description, percent) values (19, 'Vernor', 'Steampan Lid', 51);
insert into discount (discount_id, name, description, percent) values (20, 'Rosabella', 'Calvados - Boulard', 26);
insert into discount (discount_id, name, description, percent) values (21, 'Martina', 'Pheasants - Whole', 23);
insert into discount (discount_id, name, description, percent) values (22, 'Aeriel', 'Table Cloth 53x69 White', 62);
insert into discount (discount_id, name, description, percent) values (23, 'Crissy', 'Lid - High Heat, Super Clear', 90);
insert into discount (discount_id, name, description, percent) values (24, 'Clevey', 'Juice - Lemon', 76);
insert into discount (discount_id, name, description, percent) values (25, 'Tommie', 'Rice - Brown', 46);
insert into discount (discount_id, name, description, percent) values (26, 'Putnem', 'Cornflakes', 24);
insert into discount (discount_id, name, description, percent) values (27, 'Della', 'Turkey - Breast, Bone - In', 63);
insert into discount (discount_id, name, description, percent) values (28, 'Hilly', 'Spring Roll Wrappers', 6);
insert into discount (discount_id, name, description, percent) values (29, 'Muriel', 'Milkettes - 2%', 6);
insert into discount (discount_id, name, description, percent) values (30, 'Dreddy', 'Apple - Macintosh', 86);
insert into discount (discount_id, name, description, percent) values (31, 'Thomas', 'Table Cloth 72x144 White', 82);
insert into discount (discount_id, name, description, percent) values (32, 'Ariella', 'Tea - Mint', 30);
insert into discount (discount_id, name, description, percent) values (33, 'Trumaine', 'Muffin Orange Individual', 77);
insert into discount (discount_id, name, description, percent) values (34, 'Aarika', 'Beer - Steamwhistle', 25);
insert into discount (discount_id, name, description, percent) values (35, 'Clo', 'Lettuce - Arugula', 83);
insert into discount (discount_id, name, description, percent) values (36, 'Myrtice', 'Chocolate - Dark Callets', 11);
insert into discount (discount_id, name, description, percent) values (37, 'Therine', 'Pork - Back, Long Cut, Boneless', 66);
insert into discount (discount_id, name, description, percent) values (38, 'Madelina', 'Chicken - Breast, 5 - 7 Oz', 19);
insert into discount (discount_id, name, description, percent) values (39, 'Paule', 'Tea - Grapefruit Green Tea', 32);
insert into discount (discount_id, name, description, percent) values (40, 'Ronnie', 'Nut - Chestnuts, Whole', 4);
insert into discount (discount_id, name, description, percent) values (41, 'Colby', 'Pasta - Fusili Tri - Coloured', 45);
insert into discount (discount_id, name, description, percent) values (42, 'Bethina', 'Pork - Side Ribs', 34);
insert into discount (discount_id, name, description, percent) values (43, 'Alessandra', 'Wine - Chardonnay South', 26);
insert into discount (discount_id, name, description, percent) values (44, 'Daune', 'Vinegar - Sherry', 91);
insert into discount (discount_id, name, description, percent) values (45, 'Kennedy', 'Salt - Kosher', 64);
insert into discount (discount_id, name, description, percent) values (46, 'Ibby', 'Haggis', 82);
insert into discount (discount_id, name, description, percent) values (47, 'Dur', 'Towel - Roll White', 54);
insert into discount (discount_id, name, description, percent) values (48, 'Tibold', 'Apron', 16);
insert into discount (discount_id, name, description, percent) values (49, 'Kippie', 'Cookies - Fortune', 73);
insert into discount (discount_id, name, description, percent) values (50, 'Hunfredo', 'Cape Capensis - Fillet', 7);
insert into discount (discount_id, name, description, percent) values (51, 'Leroy', 'Blueberries - Frozen', 44);
insert into discount (discount_id, name, description, percent) values (52, 'Kerr', 'Oranges', 86);
insert into discount (discount_id, name, description, percent) values (53, 'Gwynne', 'Tart Shells - Barquettes, Savory', 82);
insert into discount (discount_id, name, description, percent) values (54, 'Angie', 'Trout - Hot Smkd, Dbl Fillet', 46);
insert into discount (discount_id, name, description, percent) values (55, 'Quinn', 'Bread - Petit Baguette', 17);
insert into discount (discount_id, name, description, percent) values (56, 'Rahal', 'Wine - Trimbach Pinot Blanc', 10);
insert into discount (discount_id, name, description, percent) values (57, 'Haslett', 'The Pop Shoppe - Black Cherry', 43);
insert into discount (discount_id, name, description, percent) values (58, 'Dory', 'Pork Loin Bine - In Frenched', 5);
insert into discount (discount_id, name, description, percent) values (59, 'Winn', 'Lamb - Bones', 3);
insert into discount (discount_id, name, description, percent) values (60, 'Hank', 'Chicken - White Meat, No Tender', 10);
insert into discount (discount_id, name, description, percent) values (61, 'Elinore', 'Appetizer - Mushroom Tart', 21);
insert into discount (discount_id, name, description, percent) values (62, 'Cary', 'Veal - Osso Bucco', 57);
insert into discount (discount_id, name, description, percent) values (63, 'Waldo', 'Soup - Campbells Chili Veg', 59);
insert into discount (discount_id, name, description, percent) values (64, 'Jordan', 'Wine - Chateauneuf Du Pape', 3);
insert into discount (discount_id, name, description, percent) values (65, 'Lauri', 'Garbage Bags - Clear', 53);
insert into discount (discount_id, name, description, percent) values (66, 'Ericka', 'Soup - Cream Of Broccoli', 95);
insert into discount (discount_id, name, description, percent) values (67, 'Verge', 'Sprouts - Brussel', 8);
insert into discount (discount_id, name, description, percent) values (68, 'Darby', 'Wine - Shiraz Wolf Blass Premium', 63);
insert into discount (discount_id, name, description, percent) values (69, 'Minnaminnie', 'Jolt Cola - Red Eye', 66);
insert into discount (discount_id, name, description, percent) values (70, 'Audra', 'Beer - Sleeman Fine Porter', 80);
insert into discount (discount_id, name, description, percent) values (71, 'Kaine', 'Halibut - Fletches', 19);
insert into discount (discount_id, name, description, percent) values (72, 'Harry', 'Milk 2% 500 Ml', 50);
insert into discount (discount_id, name, description, percent) values (73, 'Cammy', 'Orange Roughy 4/6 Oz', 3);
insert into discount (discount_id, name, description, percent) values (74, 'Corrine', 'Wine - Magnotta - Bel Paese White', 91);
insert into discount (discount_id, name, description, percent) values (75, 'Genny', 'Wine - Stoneliegh Sauvignon', 86);
insert into discount (discount_id, name, description, percent) values (76, 'Marita', 'Hipnotiq Liquor', 90);
insert into discount (discount_id, name, description, percent) values (77, 'Rakel', 'Vinegar - Tarragon', 45);
insert into discount (discount_id, name, description, percent) values (78, 'Fabiano', 'Swordfish Loin Portions', 24);
insert into discount (discount_id, name, description, percent) values (79, 'Elnar', 'Nut - Hazelnut, Ground, Natural', 11);
insert into discount (discount_id, name, description, percent) values (80, 'Salaidh', 'Creme De Menth - White', 33);
insert into discount (discount_id, name, description, percent) values (81, 'Ulysses', 'Juice - Pineapple, 48 Oz', 62);
insert into discount (discount_id, name, description, percent) values (82, 'Rhoda', 'Wine - Placido Pinot Grigo', 94);
insert into discount (discount_id, name, description, percent) values (83, 'Nikolaus', 'Honey - Liquid', 10);
insert into discount (discount_id, name, description, percent) values (84, 'Kaitlin', 'Duck - Breast', 89);
insert into discount (discount_id, name, description, percent) values (85, 'Claudetta', 'Tea - Mint', 17);
insert into discount (discount_id, name, description, percent) values (86, 'Tiebold', 'Sausage - Breakfast', 51);
insert into discount (discount_id, name, description, percent) values (87, 'Baillie', 'Devonshire Cream', 59);
insert into discount (discount_id, name, description, percent) values (88, 'Iona', 'Lemonade - Natural, 591 Ml', 87);
insert into discount (discount_id, name, description, percent) values (89, 'Hanni', 'Sloe Gin - Mcguinness', 71);
insert into discount (discount_id, name, description, percent) values (90, 'Ruthann', 'Extract Vanilla Pure', 50);
insert into discount (discount_id, name, description, percent) values (91, 'La verne', 'Appetizer - Mango Chevre', 30);
insert into discount (discount_id, name, description, percent) values (92, 'Cassondra', 'Wine - Rosso Del Veronese Igt', 43);
insert into discount (discount_id, name, description, percent) values (93, 'Bronny', 'Lamb Rack - Ontario', 1);
insert into discount (discount_id, name, description, percent) values (94, 'Ernestine', 'Bread Cranberry Foccacia', 15);
insert into discount (discount_id, name, description, percent) values (95, 'Fraze', 'Soup Campbells Mexicali Tortilla', 93);
insert into discount (discount_id, name, description, percent) values (96, 'Faunie', 'Potatoes - Idaho 80 Count', 47);
insert into discount (discount_id, name, description, percent) values (97, 'Basile', 'Drambuie', 54);
insert into discount (discount_id, name, description, percent) values (98, 'Fabiano', 'Chilli Paste, Sambal Oelek', 73);
insert into discount (discount_id, name, description, percent) values (99, 'Tiffany', 'Cod - Fillets', 96);
insert into discount (discount_id, name, description, percent) values (100, 'Olivia', 'Foie Gras', 82);
